### ISSUE TITLE
Add com.snowplowanalytics.snowplow.storage/redshift_config/jsonschema/1-0-0

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu-central#448]
Here is the data from the YAML:

```yaml
    - name: "My Redshift database"
      type: redshift
      host: ADD HERE # The endpoint as shown in the Redshift console
      database: ADD HERE # Name of database
      port: 5439 # Default Redshift port
      ssl_mode: disable # One of disable (default), require, verify-ca or verify-full
      table: atomic.events
      username: ADD HERE
      password: ADD HERE
      es_nodes_wan_only: false # Set to true if using Amazon Elasticsearch Service
      maxerror: 1 # Stop loading on first error, or increase to permit more load errors
      comprows: 200000 # Default for a 1 XL node cluster. Not used unless --include compupdate specified
```

In the JSON Schema I would:

* Remove `type` (it's implicit in the self-describing JSON)
* Remove `es_nodes_wan_only` (it's Elasticsearch-only)
* `ssl_mode` -> `sslMode`
* `maxerror` -> `maxError`
* `comprows` -> `compRows`
* Change `table` to `schema` (https://github.com/snowplow/snowplow/issues/2458)
