### ISSUE TITLE
Add com.snowplowanalytics.snowplow.storage/postgresql_config/jsonschema/1-0-0

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu-central#449]
Here is the YAML:

```yaml
    - name: "My PostgreSQL database"
      type: postgres
      host: ADD HERE # Hostname of database server
      database: ADD HERE # Name of database
      port: 5432 # Default Postgres port
      ssl_mode: disable # One of disable (default), require, verify-ca or verify-full
      table: atomic.events
      username: ADD HERE
      password: ADD HERE
      es_nodes_wan_only: false # Set to true if using Amazon Elasticsearch Service
      maxerror: # Not required for Postgres
      comprows: # Not required for Postgres
```

For the JSON Schema:

* Remove `type` (it's implicit in the self-describing JSON)
* Remove `es_nodes_wan_only` (it's Elasticsearch-only)
* Rename `ssl_mode` to `sslMode`
* Remove `maxerror` and `comprows`
* Change `table` to `schema` (https://github.com/snowplow/snowplow/issues/2458)
