### ISSUE TITLE
Add com.snowplowanalytics.snowplow.storage/elastic_config/jsonschema/1-0-0

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu-central#450]
Here is the YAML:

```yaml
    - name: "My Elasticsearch database"
      type: elasticsearch
      host: ADD HERE # The Elasticsearch endpoint
      database: ADD HERE # Name of index
      port: 9200 # Default Elasticsearch port - change to 80 if using Amazon Elasticsearch Service
      sources: # Leave blank to write the bad rows created in this run to Elasticsearch, or explicitly provide an array of bad row buckets like ["s3://my-enriched-bucket/bad/run=2015-10-06-15-25-53"]
      ssl_mode: # Not required for Elasticsearch
      table: ADD HERE # Name of type
      username: # Not required for Elasticsearch
      password: # Not required for Elasticsearch
      es_nodes_wan_only: false # Set to true if using Amazon Elasticsearch Service
      maxerror: # Not required for Elasticsearch
      comprows: # Not required for Elasticsearch
```

Removing the Redshift/PG fields we are left with:

```yaml
    - name: "My Elasticsearch database"
      type: elasticsearch
      host: ADD HERE # The Elasticsearch endpoint
      database: ADD HERE # Name of index
      port: 9200 # Default Elasticsearch port - change to 80 if using Amazon Elasticsearch Service
      sources: # Leave blank to write the bad rows created in this run to Elasticsearch, or explicitly provide an array of bad row buckets like ["s3://my-enriched-bucket/bad/run=2015-10-06-15-25-53"]
      table: ADD HERE # Name of type
      es_nodes_wan_only: false # Set to true if using Amazon Elasticsearch Service
```

We should:

* Remove `type` as it's implied
* Remove `sources` as it's overcomplicated (https://github.com/snowplow/snowplow/issues/2993)
* Rename `es_nodes_wan_only` to `nodesWanOnly`
* Rename `database` to `index`
* Rename `table` to `type`
